resources:
- operator.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_agent_config.yaml
  name: operator-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: operator
  newName: harbor.local/library/das-schiff-network-operator
  newTag: v1.52
