apiVersion: v1
kind: ConfigMap
data:
  controller_manager_config.yaml: |
    health:
      healthProbeBindAddress: :7081
    metrics:
      bindAddress: :7080
    webhook:
      port: 7443
    leaderElection:
      leaderElect: false
      resourceName: 186580d0.schiff.telekom.de
