resources:
- manager.yaml
- manager_master.yaml
- namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: harbor.das-schiff.telekom.de/schiff-dev/network-operator
  newTag: latest
