apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: master
  namespace: system
  labels:
    app.kubernetes.io/component: master
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: master
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: master
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: node.schiff.telekom.de/uninitialized
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      hostNetwork: true
      hostPID: true
      containers:
      - command:
        - /manager
        args:
          - -only-attach-bpf
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: controller:latest
        name: manager
        securityContext:
          privileged: true
          runAsUser: 0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 7081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/network-operator/config.yaml
          name: network-config
          subPath: config.yaml
        - mountPath: /etc/frr
          name: frr-config
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: frr-config
        hostPath:
          path: /etc/frr
          type: Directory
      - configMap:
          name: network-operator-config
        name: network-config
