apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: master
  namespace: system
  labels:
    control-plane: controller-manager
    app: network-operator-master
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app: network-operator-master
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app: network-operator-master
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      hostNetwork: true
      hostPID: true
      containers:
      - command:
        - /manager
        args:
          - -only-attach-bpf
        image: controller:latest
        name: manager
        securityContext:
          privileged: true
          runAsUser: 0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
