apiVersion: v1
kind: Service
metadata:
  name: status
  namespace: system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: worker
    app.kubernetes.io/name: network-operator
  ports:
    - protocol: TCP
      port: 7082
      targetPort: 7082
      nodePort: 30082