---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-schiff-telekom-de-v1alpha1-vrfrouteconfiguration
  failurePolicy: Ignore # TODO: Fail should be working but it is not on first boot.
  name: vvrfrouteconfiguration.kb.io
  rules:
  - apiGroups:
    - network.schiff.telekom.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vrfrouteconfigurations
  sideEffects: None
