
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: network-operator
  name: metrics
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: metrics
      # bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      # tlsConfig:
      #   insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: network-operator
