apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: network-operator
  name: metrics-service
  namespace: system
spec:
  ports:
  - name: metrics
    port: 7082
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: network-operator
