# permissions for end users to view layer2networkconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: layer2networkconfiguration-viewer-role
rules:
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - layer2networkconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - layer2networkconfigurations/status
  verbs:
  - get
