---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - ipaddresspools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - ipaddresspools/finalizers
  verbs:
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - ipaddresspools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - layer2networkconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - layer2networkconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - layer2networkconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - vrfrouteconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - vrfrouteconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - vrfrouteconfigurations/status
  verbs:
  - get
  - patch
  - update
