---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - layer2networkconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - layer2networkconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - layer2networkconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - networkconfigrevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - networkconfigrevisions/finalizers
  verbs:
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - networkconfigrevisions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - nodenetworkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - nodenetworkconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - nodenetworkconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - routingtables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - routingtables/finalizers
  verbs:
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - routingtables/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - vrfrouteconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - vrfrouteconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - vrfrouteconfigurations/status
  verbs:
  - get
  - patch
  - update
