# permissions for end users to view vrfrouteconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vrfrouteconfiguration-viewer-role
rules:
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - vrfrouteconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.schiff.telekom.de
  resources:
  - vrfrouteconfigurations/status
  verbs:
  - get
