resources:
- agent.yaml
- agent_master.yaml
- service.yaml
# - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_agent_config.yaml
  name: agent-config
- files:
  - config.yaml
  name: config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: agent
  newName: ghcr.io/telekom/das-schiff-network-operator-agent
  newTag: latest
- name: frr-exporter
  newName: ghcr.io/telekom/frr-exporter
  newTag: latest
