resources:
- configurator.yaml

generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: configurator
  newName: ghcr.io/telekom/configurator
  newTag: latest
